// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhwvvnwacxnvjjannwdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZod3Z2bndhY3hudmpqYW5ud2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTIyODEsImV4cCI6MjA2MDUyODI4MX0.AWQ1BQfFz79vO_WDLB5KvCFr-vx6mLSef4eqUmFL2ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);